name: Delete Branch on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    # 只在 PR 被合并且目标分支是 main 时运行
    # if: github.event.pull_request.merged == true && github.base_ref == 'refs/heads/main'

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          # 使用 GitHub Token
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 删除已合并的分支
          delete_closed_pr: true
          # 可选：排除的分支模式（保护重要分支）
          exclude_branches: main,develop,production