name: Delete Branch on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          # 使用正确的参数名
          delete_closed_pr: true
          exclude: "main,dev"